### ISSUE TITLE
请问： UTXO 现在可用了么？ 预计什么时候预计完整支持？

### ISSUE THREAD

**Issue by cppfuns** [snapscale/snapscale#2]
https://github.com/snapscale/snapscale/search?q=UTXO&unscoped_q=UTXO
// 请问 clutxo 源代码在哪里？
https://github.com/search?q=org%3Asnapscale+clutxo&type=code

**Comment by ryan-xeniro** [comment]
Available now, UTXO transactions are fully supported.
- [x] add UTXO-transaction model, supporting cross-transactions between the balance model and the UTXO model

---

`clutxo` is a soft link pointing to `cmd.js` in the same directory
```
ln -s cmd.js clutxo
```
- [x] The command line utility `clutxo` provides an interface to the UTXO enabled UTXO smart contract.
